name: Perl CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl: [5.24, 5.26]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup PERL
        uses: shogo82148/actions-setup-perl@2489d8800e697ae6af4c9bad542615c57eb9ad33
        with:
          perl-version: ${{ matrix.perl }}
    
      - name: Install deps
        run: cpanm --verbose --installdeps --notest .
    
      - name: Make
        run: perl Makefile.PL

      - name: Test
        run: make test
