name: Perl CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
  ci:
    name: Perl CI - test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl: [5.24, 5.26]

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
      - name: Setup PERL
        uses: shogo82148/actions-setup-perl@3d3cb73ca65d657a809d97eab324d4e4f140bf5e # v1.42.0
        with:
          perl-version: ${{ matrix.perl }}
    
      - name: Install deps
        run: cpanm --verbose --installdeps --notest .
    
      - name: Make
        run: perl Makefile.PL

      - name: Test
        run: make test
